Merge: (#17) email sign in ui
zoopi-palette/zoopi-android pull request #27
Opened 2022-04-29 05:07 UTC by limsaehyun

### 1
* intro screen에 email sign in 버튼 추가

### 2
* sign in ui 구현

https://user-images.githubusercontent.com/80076029/165887903-842112f1-28dc-4862-b19e-885fc5da74cd.mp4

2022-05-02 07:27 UTC, HoJongPARK requested changes
로그인 과정에서 이메일을 입력 후 키보드의 imeAction 으로 바로 비밀번호 TextField 를 띄우거나, 아니면 `다음` 버튼이 키보드 위에 위치해야 할 것 같음. 내리고 다음을 누르는 과정이 너무 번거로워 보임

2022-05-03 17:01 UTC, hyunjung-choi commented
저도 호종님 말에 동감합니다!
그리고 저 기능은 구현하다 보면 자주 빠뜨리는 경우가 있으니까 좀 더 신경 써주세요~!
아마 코틀린에서 몇줄만 적으면 해결되는 걸로 기억하고 있숩니다...!

2022-05-09 23:32 UTC, limsaehyun commented
### 변경사항
> 피드백 주신 대로 버튼이 키보드 위에 위치하도록 하기 위해 soft input keyboard를 사용하였습니다.

2022-05-10 02:45 UTC, HoJongPARK approved these changes

2022-05-10 08:34 UTC, hyunjung-choi approved these changes
고생하셨습니다~

2022-05-15 08:18 UTC, merged